name: Build AutoTyper

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    defaults:
      run:
        shell: msys2 {0}
    
    steps:
      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            curl
            git

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install MinGW and GCC
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm mingw-w64-x86_64-gcc

      - name: Compile autotyper.cpp
        run: |
          g++ autotyper.cpp -o autotyper.exe -mwindows -static -lstdc++ -pthread

      - name: Upload compiled exe as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Build
          path: autotyper.exe

  upload:
    name: Upload artifacts
    needs: [build]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.repository == 'lvplay2/autotyper' }}
    steps:
    - uses: actions/checkout@v4
      with:
        repository: probonopd/uploadtool

    - uses: actions/download-artifact@main
      with:
       name: Build
       path: autotyper.exe

    - name: Upload Continuous Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        UPLOAD_KEY: ${{ secrets.UPLOAD_KEY }}
      run: |
        ./upload.sh \
          ./autotyper.exe
